restaurant/urls.py
from django.urls import path

from restaurant.views import (
    index,
    CookListView,
    CookDetailView,
    CookDeleteView,
    CookCreateView,
    CookExperienceUpdateView,
    DishTypeListView,
    DishTypeDetailView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    IngredientListView,
    IngredientDetailView,
    IngredientCreateView,
    IngredientDeleteView,
    IngredientUpdateView,
    toggle_assign_to_dish,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "cook/",
        CookListView.as_view(),
        name="cook-list",
    ),
    path("cook/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cook/<int:pk>/delete/", CookDeleteView.as_view(),
         name="cook-delete"),
    path(
        "cook/<int:pk>/update/",
        CookExperienceUpdateView.as_view(),
        name="cook-update",
    ),
    path("cook/create/", CookCreateView.as_view(), name="cook-create"),
    path(
        "dish-type/",
        DishTypeListView.as_view(),
        name="dish-type-list",
    ),
    path(
        "dish-type/<int:pk>/",
        DishTypeDetailView.as_view(),
        name="dish-type-list-detail",
    ),
    path(
        "dish-type/create/",
        DishTypeCreateView.as_view(),
        name="dish-type-list-create",
    ),
    path(
        "dish-type/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dish-type-list-update",
    ),
    path(
        "dish-type/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dish-type-list-delete",
    ),
    path("dishes/", DishListView.as_view(), name="dish-list"),
    path("dish/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dish/create/", DishCreateView.as_view(), name="dish-create"),
    path("dish/<int:pk>/update/",
         DishUpdateView.as_view(),
         name="dish-update"
         ),
    path("dish/<int:pk>/delete/",
         DishDeleteView.as_view(),
         name="dish-delete"
         ),
    path(
        "dish/<int:pk>/toggle-assign/",
        toggle_assign_to_dish,
        name="toggle-dish-assign",
    ),
    path("ingredients/", IngredientListView.as_view(), name="ingredient-list"),
    path("ingredients/<int:pk>/",
         IngredientDetailView.as_view(),
         name="ingredient-detail"
         ),
    path("ingredients/create/", IngredientCreateView.as_view(),
         name="ingredient-create"),
    path("ingredients/<int:pk>/delete/", IngredientDeleteView.as_view(),
         name="ingredient-delete"),
    path("ingredients/<int:pk>/update/", IngredientUpdateView.as_view(),
         name="ingredient-update"),

]

app_name = "restaurant"

restaurant_kitchen_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("restaurant.urls", namespace="restaurant")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

restaurant/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(null=True)

    class Meta:
        ordering = ["username"]
        verbose_name = "cook"
        verbose_name_plural = "cooks"

    def __str__(self) -> str:
        return (
            f"Username: {self.username}, (Name: {self.first_name}"
            f" Surname: {self.last_name})"
            )

    def get_absolute_url(self):
        return reverse("restaurant:cook-detail", kwargs={"pk": self.pk})


class DishType(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Dish(models.Model):
    name = models.CharField(max_length=255, unique=True, blank=False)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    dish_type = models.ForeignKey(DishType, models.CASCADE)
    cooks = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="dishes"
    )

    class Meta:
        ordering = ["id"]
        verbose_name = "dish"
        verbose_name_plural = "dishes"

    def __str__(self) -> str:
        return self.name


class Ingredient(models.Model):
    name = models.CharField(max_length=255)
    dishes = models.ManyToManyField(
        Dish,
        related_name="ingredients",
        blank=True
    )

    def __str__(self):
        return self.name

restaurant/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from restaurant.models import Dish, Cook, Ingredient


class DishForm(forms.ModelForm):
    ingredients = forms.ModelMultipleChoiceField(
        queryset=Ingredient.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Dish
        fields = "__all__"


class CookCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = UserCreationForm.Meta.fields + (
            "years_of_experience",
            "first_name",
            "last_name",
        )


class CookSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username"}),

    )


class SearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"}),

    )


class CookExperienceUpdateForm(forms.ModelForm):
    class Meta:
        model = Cook
        fields = ["years_of_experience"]

    def clean_years_of_experience(self):
        years_of_experience = self.cleaned_data["years_of_experience"]
        if years_of_experience > 45:
            raise ValidationError(
                "Years of experience should not exceed 45 years"
            )
        elif years_of_experience < 1:
            raise ValidationError("Years of experience can't be less than 1")
        return years_of_experience

restaurant/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from restaurant.forms import (
    DishForm,
    CookCreationForm,
    CookSearchForm,
    SearchForm,
    CookExperienceUpdateForm,
)

from restaurant.models import (
    Cook,
    DishType,
    Dish,
    Ingredient,
)


@login_required
def index(request):
    """View function for the home page of the site."""

    num_cooks = Cook.objects.count()
    num_dish_types = DishType.objects.count()
    num_dishes = Dish.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_cooks": num_cooks,
        "num_dish_types": num_dish_types,
        "num_dishes": num_dishes,
        "num_visits": num_visits + 1,
    }

    return render(request, "restaurant/index.html", context=context)


class DishTypeListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    context_object_name = "dish_type_list"
    template_name = "restaurant/dish_type_list.html"
    paginate_by = 5
    queryset = DishType.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishTypeListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = SearchForm(initial={
            "name": name
        })
        return context

    def get_queryset(self):
        form = SearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return self.queryset


class DishTypeDetailView(LoginRequiredMixin, generic.DetailView):
    model = DishType
    context_object_name = "dish_type_list"
    template_name = "restaurant/dish_type_detail_list.html"
    paginate_by = 5


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    fields = "__all__"
    template_name = "restaurant/dish_type_form.html"
    success_url = reverse_lazy("restaurant:dish-type-list")


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    fields = "__all__"
    template_name = "restaurant/dish_type_form.html"
    success_url = reverse_lazy("restaurant:dish-type-list")


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    fields = "__all__"
    template_name = "restaurant/dish_type_confirm_delete.html"
    success_url = reverse_lazy("restaurant:dish-type-list")


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    paginate_by = 5
    queryset = Dish.objects.select_related(
        "dish_type"
    ).prefetch_related(
        "cooks"
    )

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = SearchForm(initial={
            "name": name
        })
        return context

    def get_queryset(self):
        form = SearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return self.queryset


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("restaurant:dish-list")


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("restaurant:dish-list")


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    field = "__all__"
    success_url = reverse_lazy("restaurant:dish-list")


class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    paginate_by = 5
    queryset = Cook.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CookListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("title", "")
        context["search_form"] = CookSearchForm(initial={
            "username": username
        })
        return context

    def get_queryset(self):
        queryset = self.model.objects.all()
        form = CookSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )
        return queryset


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook
    queryset = Cook.objects.all().prefetch_related("dishes__dish_type")


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    form_class = CookCreationForm
    success_url = reverse_lazy("restaurant:cook-list")


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    success_url = reverse_lazy("restaurant:cook-list")


class CookExperienceUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    form_class = CookExperienceUpdateForm
    success_url = reverse_lazy("restaurant:cook-list")


class IngredientListView(LoginRequiredMixin, generic.ListView):
    model = Ingredient
    paginate_by = 5
    queryset = Ingredient.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(IngredientListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")
        context["search_form"] = SearchForm(initial={
                "name": name,
            })
        return context

    def get_queryset(self):
        form = SearchForm(self.request.GET)
        if form.is_valid():
            return self.queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )

        return self.queryset


class IngredientDetailView(LoginRequiredMixin, generic.DetailView):
    model = Ingredient


class IngredientCreateView(LoginRequiredMixin, generic.CreateView):
    model = Ingredient
    fields = "__all__"
    success_url = reverse_lazy("restaurant:ingredient-list")


class IngredientDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Ingredient
    fields = "__all__"
    success_url = reverse_lazy("restaurant:ingredient-list")


class IngredientUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Ingredient
    fields = "__all__"
    success_url = reverse_lazy("restaurant:ingredient-list")


@login_required
def toggle_assign_to_dish(request, pk):
    cook = Cook.objects.get(id=request.user.id)
    dish = Dish.objects.get(id=pk)
    if dish in cook.dishes.all():
        cook.dishes.remove(dish)
    else:
        cook.dishes.add(dish)
    return HttpResponseRedirect(reverse_lazy(
        "restaurant:dish-detail",
        kwargs={"pk": pk})
    )

templates/restaurant/cook_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <div class="card shadow">
          <div class="card-header bg-danger text-white">
            <h1 class="card-title mb-0">Delete this cook "{{ cook.username }}" ?</h1>
          </div>
          <div class="card-body">
            <form action="" method="POST">
              {% csrf_token %}
              <input type="submit" value="Yes, delete" class="btn btn-danger me-2">
              <a href="{% url 'restaurant:cook-list' %}" class="btn btn-primary">Cancel</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/restaurant/cook_detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="card shadow">
          <div class="card-header">
            <h1 class="card-title mb-0 text-dark">Username: {{ cook.username }}</h1>
          </div>
          <div class="card-body">
            <h4 class="card-title mb-3 text-dark">Cook Information</h4>
            <p class="card-text text-dark"><strong>First name:</strong> {{ cook.first_name }}</p>
            <p class="card-text text-dark"><strong>Last name:</strong> {{ cook.last_name }}</p>
            <p class="card-text text-dark"><strong>Years of experience:</strong> {{ cook.years_of_experience }}</p>
            <p class="card-text text-dark"><strong>Is staff:</strong> {{ cook.is_staff }}</p>
          </div>
          <div class="card-footer">
            <a href="{% url 'restaurant:cook-delete' pk=cook.id %}" class="btn btn-danger me-3">
              Delete
            </a>

            <a href="{% url 'restaurant:cook-update' pk=cook.id %}" class="btn btn-secondary">
              Update years of experience
            </a>
            <a href="{% url 'restaurant:cook-list' %}" class="btn btn-primary">Back to list of Cooks</a>

          </div>
        </div>
      </div>
    </div>
    <div class="row justify-content-center mt-5">
      <div class="col-lg-8">
        <div class="card shadow">
          <div class="card-body">
            <h4 class="card-title mb-3 text-dark">Dishes</h4>
            {% for dish in cook.dishes.all %}
              <hr class="mb-4">
              <div class="row">
                <div class="col-8">
                  <h5 class="card-title mb-2 text-dark">{{ dish.name }}</h5>
                  <p class="card-text text-dark">{{ dish.description }}</p>
                  <p class="card-text text-dark"><strong>Price:</strong> {{ dish.price }}</p>
                  <p class="card-text text-dark"><strong>Type:</strong> {{ dish.dish_type.name }}</p>
                </div>
                <div class="col-4">
                  <p class="text-muted text-dark"><strong>Id:</strong> {{ dish.id }}</p>
                </div>
              </div>
            {% empty %}
              <p class="card-text text-dark">No dishes!</p>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/restaurant/cook_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <div class="card shadow">
          {% if object|yesno:"Update the cook,New cook" == "Update cook" %}
            <div class="card-header bg-primary text-white">
              <h1 class="card-title mb-0">Update the cook</h1>
            </div>
          {% else %}
            <div class="card-header bg-primary text-white">
              <h1 class="card-title mb-0">New cook</h1>
            </div>
          {% endif %}
          <div class="card-body">
            <form action="" method="post" novalidate>
              {% csrf_token %}
              {{ form|crispy }}

              <div class="d-grid mt-4">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

  <style>
      .card-header h1 {
          font-size: 2.5rem;
          font-weight: 600;
          text-transform: uppercase;
      }

      .card-body input[type="text"], .card-body input[type="number"] {
          border-radius: 10px;
          border: 2px solid #007bff;
          padding: 10px;
          font-size: 1.2rem;
          font-weight: 500;
          color: #007bff;
          background-color: #f2f2f2;
      }

      .card-body input[type="text"]:focus, .card-body input[type="number"]:focus {
          outline: none;
          box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.25);
      }

      .card-body label {
          font-size: 1.2rem;
          font-weight: 500;
          color: #333;
      }

      .card-body button[type="submit"] {
          border-radius: 10px;
          padding: 10px 20px;
          font-size: 1.2rem;
          font-weight: 500;
          text-transform: uppercase;
          background-color: #007bff;
          border: none;
      }

      .card-body button[type="submit"]:hover {
          background-color: #0062cc;
      }
  </style>

{% endblock %}

templates/restaurant/cook_list.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_filters %}
{% block content %}
  <body class="bg-image">
  <div class="container">
    <h1 class="text-center">List of chefs</h1>
    <div class="row mb-3">
      <div class="col-12 col-md-6">
        <a href="{% url 'restaurant:cook-create' %}" class="btn btn-primary">
          <span class="text-white">Create a new cook</span>
        </a>
      </div>
      <div class="col-12 col-md-6">
        <form action="" method="get" class="form-inline float-md-right">
          <div class="input-group">
            {{ search_form|crispy }}
            <div class="input-group-append">
              <button type="submit" class="btn btn-behance">
                <i class="bi bi-search">🔍</i>
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
    {% if cook_list %}
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
          <tr>
            <th>ID</th>
            <th>Username</th>
            <th>First name</th>
            <th>Last name</th>
            <th>Years of experience</th>
          </tr>
          </thead>
          <tbody>
          {% for cook in cook_list %}
            <tr>
              <td>{{ cook.id }}</td>
              <td>
                <a href="{% url 'restaurant:cook-detail' pk=cook.id %}">
                  {{ cook.username }}
                  {% if user == cook %}(Me){% endif %}
                </a>
              </td>
              <td>{{ cook.first_name }}</td>
              <td>{{ cook.last_name }}</td>
              <td>
                {% if cook.years_of_experience >= 1 %}
                  {{ cook.years_of_experience }}
                {% endif %}
              </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    {% else %}
      <p class="text-center">There are no cooks in the service.</p>
    {% endif %}
  </div>
  </body>
{% endblock %}

templates/restaurant/dish_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <div class="card shadow">
          <div class="card-body">
            <h1 class="card-title mb-3">Delete the Dish "{{ dish }}"</h1>
            <p>Are you sure you want to delete this Dish: <strong>{{ dish }}</strong>?</p>
            <form action="" method="POST">
              {% csrf_token %}
              <div class="d-grid gap-2 mt-4">
                <input type="submit" value="Yes, delete" class="btn btn-danger">
                <a href="{% url 'restaurant:dish-list' %}" class="btn btn-secondary">Cancel</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/restaurant/dish_type_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <div class="card shadow">
          <div class="card-body">
            <h1 class="card-title mb-3">Delete Dish Type "{{ dishtype }}"</h1>
            <p>Are you sure you want to delete this Dish Type: <strong>{{ dishtype }}</strong>?</p>
            <form action="" method="POST">
              {% csrf_token %}
              <div class="d-grid gap-2 mt-4">
                <input type="submit" value="Yes, delete" class="btn btn-danger">
                <a href="{% url 'restaurant:dish-type-list' %}" class="btn btn-secondary">Cancel</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/restaurant/dish_type_detail_list.html
{% extends "base.html" %}

{% block content %}
  <div class="container py-5">
    <h1 class="mb-4">Dish Type: {{ dish_type_list }}</h1>
    <div class="row">
      <div class="col-md-8">
                <a href="{% url 'restaurant:dish-type-list-update' pk=dish_type_list.id %}" class="btn btn-danger link-to-page mb-4">
            Update
          </a>
        <h2>Dishes of this type</h2>
        <hr>
        <ul class="list-group">
          {% for dish in dish_type_list.dish_set.all %}
            <a href="{% url 'restaurant:dish-detail' pk=dish.id %}">
              <li class="list-group-item">{{ dish.name }} ({{ dish.price }})</li>
            </a>
          {% empty %}
            <li class="list-group-item">No dishes found.</li>
          {% endfor %}
        </ul>
      </div>
      <div class="mt-5">
        <a href="{% url 'restaurant:dish-type-list' %}" class="btn btn-primary">Back to list of Type of Dishes</a>
      </div>
    </div>
  </div>
{% endblock %}

templates/restaurant/dish_type_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container py-5">
    <h1 class="text-center mb-4">List of Dish Types</h1>
    <div class="d-flex justify-content-end mb-4">
      <a href="{% url 'restaurant:dish-type-list-create' %}" class="btn btn-primary text-white">Add New Dish Type</a>
    </div>
    <form action="" method="get" class="form-inline mb-4">
      <div class="input-group">
        {{ search_form|crispy }}
        <div class="input-group-append">
          <button type="submit" class="btn btn-behance">
            <i class="bi bi-search">🔍</i>
          </button>
        </div>
      </div>
    </form>
    {% if dish_type_list %}
      <div class="table-responsive">
        <table class="table table-striped table-hover">
          <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th class="text-center">Edit</th>
            <th class="text-center">Delete</th>
          </tr>
          </thead>
          <tbody>
          {% for dish_type in dish_type_list %}
            <tr>
              <td>{{ dish_type.id }}</td>
              <td>
                <a href="{% url 'restaurant:dish-type-list-detail' pk=dish_type.id %}" class="text-decoration-none">
                  {{ dish_type.name }}
                </a>
              </td>
              <td class="text-center">
                <a href="{% url 'restaurant:dish-type-list-update' pk=dish_type.id %}"
                   class="btn btn-primary btn-sm text-white">
                  Edit
                </a>
              </td>
              <td class="text-center">
                <form action="{% url 'restaurant:dish-type-list-delete' pk=dish_type.id %}" method="get">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-danger btn-sm">
                    Delete
                  </button>
                </form>
              </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    {% else %}
      <p>There are no Dish Types in the service.</p>
    {% endif %}
  </div>
{% endblock %}

templates/restaurant/ingredient_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <div class="card shadow">
          <div class="card-body">
            <h1 class="card-title mb-3">Delete this Ingredient "{{ ingredient }}"</h1>
            <p>Are you sure you want to delete this Ingredient: <strong>{{ ingredient }}</strong>?</p>
            <form action="" method="POST">
              {% csrf_token %}
              <div class="d-grid gap-2 mt-4">
                <input type="submit" value="Yes, delete" class="btn btn-danger">
                <a href="{% url 'restaurant:ingredient-list' %}" class="btn btn-secondary">Cancel</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/restaurant/ingredient_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="container py-5">
    <h1>Ingredient Detail: {{ ingredient }}</h1>
    <a href="{% url 'restaurant:ingredient-update' pk=ingredient.id %}" class="btn btn-danger link-to-page mb-4">
      Update
    </a>

    <h2>Dishes that use {{ ingredient }}:</h2>
    <ul>
      {% for dish in ingredient.dishes.all %}
        <li>{{ dish.name }}</li>
      {% endfor %}
    </ul>

    <div class="mt-5">
      <a href="{% url 'restaurant:ingredient-list' %}" class="btn btn-primary">Back to Ingredients</a>
    </div>
  </div>
{% endblock %}

templates/restaurant/ingredient_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

  <div class="container py-5">
    <h1 class="text-center mb-4">List of Ingredients</h1>
    <div class="d-flex justify-content-end mb-4">
      <a href="{% url 'restaurant:ingredient-create' %}" class="btn btn-primary text-white">Add new ingredient</a>
    </div>
    <form action="" method="get" class="form-inline mb-4">
      <div class="input-group">
        {{ search_form|crispy }}
        <div class="input-group-append">
          <button type="submit" class="btn btn-behance">
            <i class="bi bi-search">🔍</i>
          </button>
        </div>
      </div>
    </form>
    {% if ingredient_list %}
      <div class="table-responsive">
        <table class="table table-striped table-bordered">
          <thead class="thead-dark">
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Dishes</th>
            <th class="text-center">Edit</th>
            <th>Delete</th>
          </tr>
          </thead>
          <tbody>
          {% for ingredient in ingredient_list %}
            <tr>
              <td>{{ ingredient.id }}</td>
              <td>
                <a href="{% url 'restaurant:ingredient-detail' pk=ingredient.id %}"
                   class="text-decoration-none">{{ ingredient.name }}</a>
              </td>
              <td>
                <ul class="list-unstyled">
                  {% for dish in ingredient.dishes.all %}
                    <li>{{ dish.name }}</li>
                  {% endfor %}
                </ul>
              </td>
              <td class="text-center">
                <a href="{% url 'restaurant:ingredient-update' pk=ingredient.id %}"
                   class="btn btn-primary btn-sm text-white">
                  Edit
                </a>
              </td>
              <td>
                <form action="{% url 'restaurant:ingredient-delete' pk=ingredient.id %}" method="get">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-danger btn-sm">
                    <i class="bi bi-trash"></i> Delete
                  </button>
                </form>
              </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    {% else %}
      <div class="alert alert-warning">
        <p>There are no Ingredients in the service.</p>
      </div>
    {% endif %}
  </div>
{% endblock %}